### ISSUE TITLE
Can Not run "mvn clean deploy" with current source repository.

### ISSUE THREAD

**Issue by cagreek** [jhipster/jhipster-loaded#10]
Been having trouble with hot load/liquibase functionality with the main yeoman jhipster generated code.  thought id try to compile the jhipster-loaded jar and use that but i'm having trouble compiling it with the basic clean and deploy command "mvn clean deploy"

Thanks in Advance.
Andy

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] jhipster
[INFO] common
[INFO] core
[INFO] agent
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building jhipster 0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jhipster ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ jhipster ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jhipster ---
[INFO] Installing C:\Users\a\Documents\workspace-sts-3.3.0.RELEASE\test02\jhipster-loaded-master\pom.xml to C:\Users\a.m2\repository\io\github\jhipster\loaded\jhipster\0.9-SNAPSHOT\jhipster-0.9-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ jhipster ---
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/github/jhipster/loaded/jhipster/0.9-SNAPSHOT/maven-metadata.xml

Uploading: https://oss.sonatype.org/content/repositories/snapshots/io/github/jhipster/loaded/jhipster/0.9-SNAPSHOT/jhipster-0.9-20140705.233737-1.pom
2/11 KB  
4/11 KB  
6/11 KB  
8/11 KB  
10/11 KB  
11/11 KB   

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jhipster .......................................... FAILURE [4.315s]
[INFO] common ............................................ SKIPPED
[INFO] core .............................................. SKIPPED
[INFO] agent ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.698s
[INFO] Finished at: Sat Jul 05 16:37:38 PDT 2014
[INFO] Final Memory: 12M/112M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project jhipster: Failed to deploy artifacts: Could not transfer artifact io.github.jhipster.loaded:jhipster:pom:0.9-20140705.233737-1 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/io/github/jhipster/loaded/jhipster/0.9-SNAPSHOT/jhipster-0.9-20140705.233737-1.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by jmirc** [comment]
You are not allowed to deploy on OSS.
