### ISSUE TITLE
Unable to package this project

### ISSUE THREAD

**Issue by binduwavell** [jhipster/jhipster-loaded#15]
I cloned this project and ran mvn package and got the following error:

[ERROR] Failed to execute goal on project jhipster: Could not resolve dependencies for project io.github.jhipster.loaded:jhipster:pom:0.12-SNAPSHOT: Failed to collect dependencies for [org.springframework:springloaded:jar:1.2.1.BUILD-SNAPSHOT (compile), org.springframework:spring-context:jar:4.0.5.RELEASE (provided), org.springframework:spring-webmvc:jar:4.0.5.RELEASE (provided), org.springframework:spring-orm:jar:4.0.5.RELEASE (provided), org.springframework:spring-web:jar:4.0.5.RELEASE (provided), org.springframework.data:spring-data-jpa:jar:1.5.0.RELEASE (provided), org.springframework.data:spring-data-mongodb:jar:1.4.1.RELEASE (provided), org.springframework.boot:spring-boot-autoconfigure:jar:1.0.0.RC4 (provided), org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.FINAL (provided), javax.inject:javax.inject:jar:1 (provided), org.javassist:javassist:jar:3.18.0-GA (provided), javax.servlet:javax.servlet-api:jar:3.0.1 (provided), com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.3.1 (provided), commons-lang:commons-lang:jar:2.6 (provided), commons-io:commons-io:jar:2.4 (provided), org.liquibase:liquibase-core:jar:3.0.8 (provided), org.liquibase.ext:liquibase-hibernate4:jar:3.3 (provided)]: Failed to read artifact descriptor for org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.FINAL: Could not transfer artifact org.hibernate.javax.persistence:hibernate-jpa-2.1-api:pom:1.0.0.FINAL from/to spring-snapshots-local (http://repo.spring.io/libs-snapshot-local/): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/hibernate/javax/persistence/hibernate-jpa-2.1-api/1.0.0.FINAL/hibernate-jpa-2.1-api-1.0.0.FINAL.pom. Return code is: 409, ReasonPhrase:Conflict. -> [Help 1]

I disabled my settings.xml that causes me to relay through our artifactory and got the same error.

**Comment by Toub** [comment]
Very annoying bug, how to contribute?

**Comment by jmirc** [comment]
Let me know if you still have any problem but it is not related to JHipster

**Comment by Toub** [comment]
Bug reproduced, and this time I was able to find the problem: a case related one in hibernate-jpa version.
