### ISSUE TITLE
What is jhipster-loaded status ?

### ISSUE THREAD

**Issue by kevintrannz** [jhipster/jhipster-loaded#27]
It seems this project becomes legacy ?

**Comment by jdubois** [comment]
Sorry, I just added a "DEPRECATED" in the project's description.
This isn't used or maintained anymore:
- it has lots of bugs
- it doesn't work with Java 8, and we only support Java 8 now
- Spring Boot devtools have a "hot reload" feature that basically does the same thing, without all the trouble, and this what we use now.
