### ISSUE TITLE
[Enhancement] Disable db change set generation param

### ISSUE THREAD

**Issue by daniel79** [jhipster/jhipster-loaded#5]
Sometimes auto db change set generation breaks manually created tables so it would be useful to disable it by running param.

**Comment by jmirc** [comment]
Sorry for the late answer.

Could you please send me an example to be able to reproduce it? I would like to understand your issue.

**Comment by jmirc** [comment]
I would like to make a new release and I would like to include this bug. 
Could you please help me to reproduce the bug?

**Comment by jmirc** [comment]
Close this bug. Please reopen it and add it more information
