### ISSUE TITLE
changelog is executed twice

### ISSUE THREAD

**Issue by wollodev** [jhipster/jhipster-loaded#6]
Related to https://github.com/jhipster/generator-jhipster/issues/276 I figured out that the changelog is executed twice. First with hotreloaded and when the application is restarted

Why? Because of the filename in the databasechangelog table. 
With hotreload I get: file:/Users/userx/Desktop/myProject/src/main/resources/config/liquibase/changelog/db-changelog-003.xml
and in my master.xml the filename is specified as:
classpath:config/liquibase/changelog/db-changelog-003.xml

As long it's not equal, liquibase tries to execute the changelog a second time.

Here is a related discussion: http://forum.liquibase.org/topic/why-does-the-change-log-contain-the-file-name

**Comment by jmirc** [comment]
Sorry for the late answer.

I was not aware about this problem. I will check to see how to avoid it.
Thanks

**Comment by jmirc** [comment]
I extended the XMLChangeLogSerializer to be able to add to the databaseChangeLog and the changeSet elements the logicalFilePath attribute to none.
